# Generated by Django 3.0.7 on 2020-06-28 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('restaurant', models.CharField(max_length=20)),
                ('numberOfPeople', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('expense', models.CharField(max_length=100)),
                ('offers', models.CharField(max_length=100)),
                ('waitTime', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'waitTime',
            },
        ),
    ]
